### ISSUE TITLE
Custom domain support without the need to have the provider name in domain

### ISSUE THREAD

**Issue by theoludwig** [material-extensions/material-icons-browser-addon#5]
Hello! :wave:
Thank you for continuing the maintenance of this browser extension.

If I understand correctly, https://github.com/material-extensions/material-icons-browser-addon/pull/1, the way it works is that it detect if there is `gitea`, `gitlab`, etc. in the domain name so for example `gitea.theoludwig.fr`, however if it's not in the domain name, for example `git.theoludwig.fr`, it doesn't detect, and show a message saying that it is not supported.

We should allow any domain name, instead of saying it is not supported, it should let the user manually select the provider.

**Comment by theoludwig** [comment]
cc @mikeydevelops

**Comment by mikeydevelops** [comment]
It is supposed to check for matching provider based on the `detect` property in each provider config. It is not based on domain, the domain just auto selects the provider when a custom domain is being added. Will check and fix it if it is not like that.
